import {StyleSheet} from 'react-native';
import {
  SAFE_AREA_PADDING,
  SCREEN_WIDTH,
  CONTENT_SPACING,
  BUTTON_SIZE,
  SAFE_BOTTOM,
  CAPTURE_BUTTON_PADDING,
} from '@src/constants';

export default StyleSheet.create({
  acquireContainer: {
    flex: 1,
    backgroundColor: 'black',
  },
  screenNavContainer: {
    flex: 1,
    backgroundColor: 'black',
  },
  cameraContainer: {
    flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'column',
    backgroundColor: 'translucent',
  },
  topCenterRow: {
    position: 'absolute',
    right: 0,
    left: 0,
    top: SAFE_AREA_PADDING.paddingTop,
    backgroundColor: 'transparent',
  },
  topRightRow: {
    position: 'absolute',
    right: SAFE_AREA_PADDING.paddingRight,
    top: SAFE_AREA_PADDING.paddingTop,
    backgroundColor: 'transparent',
  },
  bottomRow: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-end',
    position: 'absolute',
    bottom: SAFE_AREA_PADDING.paddingBottom + 33,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingTop: 5,
    paddingBottom: 5,
  },
  bottomRowControl: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    marginBottom: 5,
  },
  bottomRowControlLeft: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    backgroundColor: 'transparent',
    position: 'absolute',
    left: 0,
    bottom: 0,
    padding: 0,
    margin: 0,
  },
  bottomRowControlCenter: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'transparent',
    position: 'absolute',
    bottom: 0,
    width: 80,
    padding: 0,
    margin: 0,
  },
  bottomRowControlRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    backgroundColor: 'transparent',
    position: 'absolute',
    right: 0,
    bottom: 0,
    padding: 0,
    margin: 0,
  },
  bottomRowControlLeftLeft: {
    flex: 1,
    marginBottom: 20,
    marginLeft: 20,
    backgroundColor: 'transparent',
  },
  bottomRowControlLeftCenter: {
    flex: 1,
    marginBottom: 25,
    backgroundColor: 'transparent',
  },
  bottomRowControlLeftRight: {
    flex: 1,
    marginBottom: 20,
    marginRight: 20,
    backgroundColor: 'transparent',
  },
  squre: {
    marginBottom: CONTENT_SPACING,
    width: BUTTON_SIZE,
    height: BUTTON_SIZE,
    borderRadius: 10,
    backgroundColor: 'rgba(140, 140, 140, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonChecked: {
    marginBottom: CONTENT_SPACING,
    width: BUTTON_SIZE,
    height: BUTTON_SIZE,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonDefault: {
    marginBottom: CONTENT_SPACING,
    width: BUTTON_SIZE,
    height: BUTTON_SIZE,
    borderRadius: 10,
    backgroundColor: 'rgba(140, 140, 140, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  artItemContainer: {
    flexShrink: 1,
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    backgroundColor: 'transparent',
  },
  artItemContainer2: {
    width: SCREEN_WIDTH,
    backgroundColor: 'transparent',
  },
  artImage: {
    height: 47,
    width: 47,
    borderWidth: 1.5,
    borderRadius: 9,
  },
});
